### PR TITLE
Login page ui made

### LINKED ISSUE #9: Create login page for the application
You need to create a login page for the application.

### PR DESCRIPTION
**Pull request by Rukmini-Meda**
Fixes #9 

I have made the basic login screen UI. Any suggestions are welcome. Please review.
The following are the screenshots of the login screen

loginpage1

loginpage2

loginpage3

loginpage4

loginpage5

### CODE REVIEW

**Comment by Rukmini-Meda** [comment]
Also, the UI can be improved further based on the theme of the app. If you suggest anything about it, I can work on improving the UI to make it look better.

**Comment by tanmayrauth** [comment]
Its looking pretty much simple UI. Let me grab some example for you.

**Comment by tanmayrauth** [comment]
image

vertical flow
1st field - phone no
2nd field - password
login button
forgot password?

**Review by tanmayrauth — COMMENTED** [review]
add a dummy logo for now and try to maintain the colour gradient as in sample. 
After some time we will try to refactor the registration ui as well in similar lines
Don't worry different issue with hard label will be assigned to it

**Comment by Rukmini-Meda** [comment]
Okay. Yes, I forgot about "forgot password" field. Can I use any logo maker online to make a logo for the app instead?

**Comment by tanmayrauth** [comment]
yeah sure. one thing wanted to highlight. Please try to maintain the gradient flow of background (means the colour changes from top to bottom)

**Comment by ankitshaw** [comment]
you can use material.io

**Comment by Rukmini-Meda** [comment]
Okay, I will check it out

**Comment by Rukmini-Meda** [comment]
Can I use other colors for gradient ?

**Comment by ankitshaw** [comment]
> Can I use other colors for gradient ?

yes

**Comment by tanmayrauth** [comment]
@Rukmini-Meda were you able to make any progress?

**Comment by Rukmini-Meda** [comment]
Yes, I am working on it. Sorry for being late. I will make the PR tonight.

**Comment by Rukmini-Meda** [comment]
Actually, when I run flutter run, it's taking too long suddenly, dont know why. It's been running for so long I am not able to continue in my work. Can you help me in this? I upgraded flutter just when i was going to run it and then it threw some build error. I didn't go through it properly, but re ran it. And now it's going on forever. This didnt happen with me anytime before. Please help.

**Comment by Rukmini-Meda** [comment]
Screenshot (125)


Screenshot (126)

This is the output of flutter run -v. I am not able to understand the error.

**Comment by bharatmk2567** [comment]
@Rukmini-Meda can you just clean project and rerun it again?
Maybe it will solve issue

**Comment by Rukmini-Meda** [comment]
@bharatmk257 Thank you. Its resolved.

**Comment by Rukmini-Meda** [comment]
Screenshot (129)


Screenshot (130)


Can you take a look at these? I have made with and without gradient. In the without gradient screen, only appbar has gradient. Also, the splash screen has black text and red circular loader. So, I was thinking may be I should try using those colors. Shall I try any combination like that?

**Comment by Rukmini-Meda** [comment]
Can you suggest me any more ideas?

**Comment by Rukmini-Meda** [comment]
I will update you one more design using red and white in the theme in a little while. I will try using solid color instead of gradient this time.

**Comment by bharatmk2567** [comment]
Okay

**Comment by tanmayrauth** [comment]
> Can you suggest me any more ideas?

1. We don't need appbar for login and signup screen.
2. Please try to match color gradient as that of example.
2. even the text box should match the example with clipart at left in both of the boxes
3. dont need signup link at bottom ( because after splash screen there will be button for it)

**Comment by Rukmini-Meda** [comment]
> > Can you suggest me any more ideas?
> 
> 1. We don't need appbar for login and signup screen.
> 2. Please try to match color gradient as that of example.
> 3. even the text box should match the example with clipart at left in both of the boxes
> 4. dont need signup link at bottom ( because after splash screen there will be button for it)

I think a link to signup can be there if user wants to navigate to signup when he accidentally got into login. What do you say?

**Comment by tanmayrauth** [comment]
> > > Can you suggest me any more ideas?
> > 
> > 
> > 
> > 1. We don't need appbar for login and signup screen.
> > 2. Please try to match color gradient as that of example.
> > 3. even the text box should match the example with clipart at left in both of the boxes
> > 4. dont need signup link at bottom ( because after splash screen there will be button for it)
> 
> I think a link to signup can be there if user wants to navigate to signup when he accidentally got into login. What do you say?

Works! keep the format and font same as that of example

**Comment by Rukmini-Meda** [comment]
Screenshot (134)


Screenshot (133)


Please look at these. I have made it just like the example except for a few changes in format. If there is need of any more changes, please let me know.

**Comment by Rukmini-Meda** [comment]
@tanmayrauth @ankitshaw @bharatmk257  Once I get confirmation that it's fine, I will commit the final code.

**Comment by Rukmini-Meda** [comment]
@tanmayrauth @ankitshaw @bharatmk257 I have committed the final code. Please review and merge soon so that I can start working on the backend part. Thank you.

**Comment by ankitshaw** [comment]
I dont think we need the phone icon and input labels as well. rather use input placeholder so that it looks more uniform. What say?

**Comment by bharatmk2567** [comment]
I think we don't need a phone icon but labels will be okay Easy for users

**Comment by Rukmini-Meda** [comment]
Okay, so should I remove the phone icon?

**Comment by bharatmk2567** [comment]
Yes remove phone icon

**Comment by Rukmini-Meda** [comment]
Screenshot (135)


How about it now? Shall I commit the code?

**Comment by tanmayrauth** [comment]
looks good for now. Few changes are still there to be made in order to match example. But we can take it as later enhancements. Will review the code and get it merged in some time.

**Comment by Rukmini-Meda** [comment]
I did not match the example precisely because it was meant for registration rather than login. I will commit the final code now to review.

**Comment by Rukmini-Meda** [comment]
@tanmayrauth @ankitshaw In the PR of register backend, the assignee has included the email field which was not in our plan before. Actually, firebase backend works with email and password, so he might have changed it... so shall I change the input field of phone to email as it becomes easy to work with the backend as well.

**Comment by tanmayrauth** [comment]
Yep, Can be done

**Pull request merged**
