### PR TITLE
Registration page ui

### LINKED ISSUE #10: Create a registration page for the application

### PR DESCRIPTION
**Pull request by Rukmini-Meda**
Fixes #10 

Changes made
- Button for registration page added in main.dart file
- Registration form is added in register.dart file

Files changed
- main.dart
- register.dart

Below are the screenshots of the UI of the registration page

registration_page1

registration_page2

I am working on the validation part and will commit it in a few hours.

Please review.

Thank you.

### CODE REVIEW

**Comment by Rukmini-Meda** [comment]
Please help me to rectify the checks. And I was planning to include two more things - 1. A check box for accepting terms and conditions, 2. A checkbox if one wants to volunteer for any help. I need review from mentors whether I can go ahead with the above 2 ideas. I included only city field and not country field, shall I add a country field as well? I will commit the validation part tomorrow. Please let me know if it can be modified or improved further.

**Comment by tanmayrauth** [comment]
@Rukmini-Meda Please solve merge conflicts

**Comment by Rukmini-Meda** [comment]
Okay, will do it.

**Comment by ankitshaw** [comment]
> Okay, will do it.

also provide snapshot of main activity view

**Comment by pravinyo** [comment]
@Rukmini-Meda It feels like we are gathering `quite lots of details` from the user. Is it necessary to collect that many details for the app to function properly. 

@tanmayrauth  and @ankitshaw , Do we really need that many details for the app to work? Do we have any `privacy policy` dealing with those details?

**Comment by Rukmini-Meda** [comment]
I thought they were the essential details required for an app like travel-safe. I will make any changes as discussed and proposed by mentors.

**Comment by Rukmini-Meda** [comment]
And of course I have forgotten to add a password field which is atmost necessary. I will add the password field. About the remaining fields, I will make changes once mentors reply and decide about it.

**Comment by Rukmini-Meda** [comment]
> > Okay, will do it.
> 
> also provide snapshot of main activity view

Can I know what's meant by main activity view? Did you mean the main screen?

**Comment by ankitshaw** [comment]
> > > Okay, will do it.
> > 
> > 
> > also provide snapshot of main activity view
> 
> Can I know what's meant by main activity view? Did you mean the main screen?

Yes Rukmini, I meant that.

After discussion with Tanmay and the project admin we decided that following fields would be necessary for now. You can remove the others. Those details will have to added by user after logging in to their account. :
1. Full Name
2. Password
3. Mobile number

**Comment by Rukmini-Meda** [comment]
Okay, I will make changes. Do I have to make any changes in main view other than adding a button navigating to the registration page?

**Comment by Rukmini-Meda** [comment]
Will login happen using phone number and password? Or should I add anything else like username?

**Comment by ankitshaw** [comment]
> Will login happen using phone number and password? Or should I add anything else like username?

phone number will be used

**Comment by ankitshaw** [comment]
> Okay, I will make changes. Do I have to make any changes in main view other than adding a button navigating to the registration page?

no, that's how we would like to keep for now.

**Comment by pravinyo** [comment]
> > Will login happen using phone number and password? Or should I add anything else like username?
> 
> phone number will be used

@tanmayrauth  and @ankitshaw , I think implementing our login feature could be time consuming activity. If possible we can use Auth0. It has quite good security feature like login via password + social login. Using services like this will help us save time in implementing our own security system

**Comment by ankitshaw** [comment]
> Auth0

Thanks for you suggest, backend implementation is out of scope for this issue.

**Comment by Rukmini-Meda** [comment]
I have made changes as you said.
The following are the screenshots of the app

registerpage_1


registerpage_2


registerpage_3


registerpage_4


registerpage_5


Please review and merge. Thank you.

**Review by ankitshaw — APPROVED** [review]
looks good to me

**Comment by tanmayrauth** [comment]
Looks good to me even. @Rukmini-Meda will you be working on the backend part even ?
Since you have developed the UI integrating the backend stuff should be easier for you.

**Comment by Rukmini-Meda** [comment]
I will be happy to work. But there's a separate issue for backend. Do you want me to work on backend as well in this issue? Or will there be another issue created that can be assigned to me?

**Review by tanmayrauth — APPROVED** [review]

**Pull request merged**
