### PR TITLE
Login firebase authentication #59 resolved

### LINKED ISSUE #59: User Login ( Backend )
User authentication backend integration with UI

### PR DESCRIPTION
**Pull request by Rukmini-Meda**
Fixes #59 

Files changed/added/removed:

- components/.dart_tool/package_config.json
- components/.flutter-plugins
- components/.flutter-plugins-dependencies
- components/.packages
- components/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
- components/ios/Flutter/Generated.xcconfig
- components/ios/Flutter/flutter_export_environment.sh
- components/ios/Runner/GeneratedPluginRegistrant.h
- components/ios/Runner/GeneratedPluginRegistrant.m
- master/android/settings_aar.gradle

 **Files related to implementation:**
- master/lib/authentication.dart
- master/lib/screens/home.dart

Tools/Frameworks:
- Flutter
- Firebase

**Changes made:**
- Added firebase implementation for phone authentication

**Tasks to be done:**
- Verification to be done as SHA-1 key hasnt yet been added to firebase console
- Changes in UI accordingly

@ankitshaw @tanmayrauth

### CODE REVIEW

**Comment by Rukmini-Meda** [comment]
I still am working on it. SHA -1 key has to be added to the project settings for me to verify the app. Working on the same. WIll update once its done.

**Comment by bharatmk2567** [comment]
@tanmayrauth We need to generate SHA-1 and add it to firebase project to verify this PR

**Comment by Rukmini-Meda** [comment]
**Screenshots:**

Screenshot (185)

Image of the login screen

Screenshot (186)

Screenshot (187)

Images of the login screen with appropriate errors

Screenshot (188)

Image of dialog for entering sms code

Screenshot (189)

Image of the screen redirected after successful login.

Screenshot (190)

Image after logout.

Screenshot (191)

Image when an invalid sms code is entered by user.

**Comment by Rukmini-Meda** [comment]
@ankitshaw @tanmayrauth @bharatmk257 Please review my work for any further changes and merge.

**Comment by Rukmini-Meda** [comment]
@ankitshaw @tanmayrauth @bharatmk257 Should I commit the files that are changed in components folder and android folder in master as well?

**Comment by Rukmini-Meda** [comment]
> @tanmayrauth We need to generate SHA-1 and add it to firebase project to verify this PR

Yes, the travel-safe project has no SHA-1 key added to it.

**Comment by tanmayrauth** [comment]
@bharatmk257 @ankitshaw shall we merge this PR? It seems good to me.

**Comment by bharatmk2567** [comment]
Yeah it is working
And do add SHA-1 key to firebase

**Comment by tanmayrauth** [comment]
> Yeah it is working
> And do add SHA-1 key to firebase

@ankitshaw Could you help on this

**Pull request merged**
