### PR TITLE
Updated the Readme

### PR DESCRIPTION
**Pull request by Nidakhan786**

### CODE REVIEW

**Review by ankitshaw — APPROVED** [review]
Looks fine to me

**Comment by ankitshaw** [comment]
A small change needed, can you please add the logo of travel safe before getting started section. The logo can be found in directory .github. Also there is another readme file in the master module remove that. Thanks, make sure pull the changes.

**Comment by Nidakhan786** [comment]
@ankitshaw @tanmayrauth  please do have a look and let me know if any more changes are required.

**Review by tanmayrauth — APPROVED** [review]

**Comment by ankitshaw** [comment]
@all-contributors bot please add @himanshusharma89  for doc

**Comment by ankitshaw** [comment]
@all-contributors bot please add @Nidakhan786  for doc

**Pull request merged**
