### PR TITLE
About Us Screen developed - fixes #56

### LINKED ISSUE #56: About Us UI activity
**Aesthetically good** UI that provide details about

logo
Apps working 
Need of app
Mission of app
Contributor's list ( circular icon grid at the end of the above details, linked to their github account fetched from firebase db)

### PR DESCRIPTION
**Pull request by Rukmini-Meda**
Fixes #56 

**Files changed:**
- main.dart
- aboutUs.dart
- pubspec.yaml
- introPage.dart

**Technologies used:**
- Flutter
- Firebase

**Screenshots:**

About_us_1

About_us_2

About_us_3

About_us_4

About_us_5

This is the response on clicking on a contributor in the list:

About_us_7

Its redirected to the particular contributor's github profile.

About_us_6

**Remarks:**

I have developed the about us screen. It dynamically fetches the data from firestore about the contributor's list. I have created a button for about us screen in main.dart. Just to test, I have changed the navigation in intropage to about us screen instead of login page. I have mentioned 4 contributors just for sake. Just updating the firestore with contributors is enough if we need to add more.

@ankitshaw @tanmayrauth

### CODE REVIEW

**Comment by tanmayrauth** [comment]
Looks good to me.

**Comment by ankitshaw** [comment]
few of points @Rukmini-Meda 
1. we need to make sure the previous drop down is closed when a new card is clicked
2. why google service json was removed

**Comment by Rukmini-Meda** [comment]
> few of points @Rukmini-Meda 
> 1. we need to make sure the previous drop down is closed when a new card is clicked
> 2. why google service json was removed

@ankitshaw 

1. It can be anyway, you can view multiple cards at the same time or close some and view others. There are no issues concerned with it as far as I have thought of.
2. I will add the Google-services.json in the commit. I replaced the file of my project with the file of travel safe project. I have added the file but forgot to commit.

**Comment by Rukmini-Meda** [comment]
@ankitshaw @tanmayrauth Please merge this PR if there are no changes required.

**Comment by ankitshaw** [comment]
@all-contributors bot please add @Rukmini-Meda  for code

**Pull request merged**
