### PR TITLE
 An Activity with all helpline numbers

### PR DESCRIPTION
**Pull request by akshaydhiran**
Updated Changes !!

### CODE REVIEW

**Comment by tanmayrauth** [comment]
Please share screenshots

**Comment by tanmayrauth** [comment]
@akshaysingh5 It really doesn't make sense to raise new PR without the review comments integrated.

**Comment by akshaydhiran** [comment]
Okay @tanmayrauth and why it is invalid @ankitshaw?  What's wrong now?

**Comment by tanmayrauth** [comment]
For the same reason. Please let us know will you be able to work on enhancement or not. Or do you need any help from mentor on personal level even tht will be provided.

But please working accordingly to review suggested.

**Comment by akshaysingh5** [comment]
Flutter is very new to me but I have experience in Android Development using Java. I tried very hard to solve this issue. Every time, I tried it doesn't well. Although only two projects are related to Mobile App in entire this season of GSSOC. I am tired now, Yes Help is required.

**Comment by ankitshaw** [comment]
You have not incorporated the changes I had suggested last time. Please ask for help in the slack group if you really want to work on this some one from the mentors will help you. Closing this PR...

**Pull request closed without merging**
