### PR TITLE
Shared Location Screen

### LINKED ISSUE #48: Currently shared location Screen (UI)
An list UI with all the details about the users who have share. Similar to this.
Just develop a similar UI. Backed will be a different issue raised.
image

### PR DESCRIPTION
**Pull request by himanshusharma89**
image

@tanmayrauth @ankitshaw 
#48
The full working screen is created:
- I have used faker for getting fake user name 
- The sidebar sorting is also working

### CODE REVIEW

**Comment by himanshusharma89** [comment]
Hello @tanmayrauth @ankitshaw , can you look into this PR

**Comment by ankitshaw** [comment]
@tanmayrauth  I think we can close this issue, unless you have any suggestions

**Comment by tanmayrauth** [comment]
I guess there are many redundant things which will not be used now. 
1. vertical name tab at left.
2. search bar 
3. matches word and icon

Wanted to understand does the list and block view works ?
once which is at top left horizontal to matches
( if it works keep it else remove it )

**Review by tanmayrauth — COMMENTED** [review]
Please get this changes done then we can focus over backend

**Comment by himanshusharma89** [comment]
The vertical name scroll view works, it'll change alphabets as we scroll down through different names. I have not implemented the top search bar. I have just focused on the UI.

**Comment by himanshusharma89** [comment]
> I guess there are many redundant things which will not be used now.
> 
> 1. vertical name tab at left.
> 2. search bar
> 3. matches word and icon
> 
> Wanted to understand does the list and block view works ?
> once which is at top left horizontal to matches
> ( if it works keep it else remove it )

Should I remove these things?

**Comment by tanmayrauth** [comment]
> > I guess there are many redundant things which will not be used now.
> > 
> > 1. vertical name tab at left.
> > 2. search bar
> > 3. matches word and icon
> > 
> > Wanted to understand does the list and block view works ?
> > once which is at top left horizontal to matches
> > ( if it works keep it else remove it )
> 
> Should I remove these things?

yes.

**Comment by himanshusharma89** [comment]
ezgif com-video-to-gif (4)
@tanmayrauth Check it now.

**Comment by tanmayrauth** [comment]
@himanshusharma89 
We don't need the vertical name tab as well mentioned on point 1.
Also jst keep a appbar with name as **Shared Locations**

**Comment by himanshusharma89** [comment]
@tanmayrauth check it now.

**Comment by tanmayrauth** [comment]
can you share screenshot. I hope you have added the app bar as well

**Comment by tanmayrauth** [comment]
@himanshusharma89 Can you share screenshots. So if all is good then we can get it merged.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 Can you share screenshots. So if all is good then we can get it merged.

Sorry, I forgot to add it: 
image

We can have it added in a list in future.

**Comment by tanmayrauth** [comment]
Looks good. But remember to remove faker when we integrate backed.

**Comment by himanshusharma89** [comment]
> Looks good. But remember to remove faker when we integrate backed.

Sure, I'll remove it. And also do add the `gssoc` and the level label to this PR

**Comment by ankitshaw** [comment]
@all-contributors bot please add @himanshusharma89  for code

**Pull request merged**
